Milestone1
Adewunmi97/Awesome_books pull request #1
Opened 2021-09-13 15:25 UTC by Adewunmi97

- Implemented only a basic UI with plain HTML
- Created a collection that keeps a list of books (hint: you can use an array of objects for that).
- Created a function to add a new book to the collection, with title and author.
- Created a function to remove a book from the collection (hint: you can use the array filter() method).
- Displayed all books saved in the collection in the top part of the page.
- When a user clicks the "Add" button:
- A new book is added to the collection.
- The new book is displayed on the page.
- When a user clicks the "Remove" button:
- The correct book is removed from the collection.
- The correct book disappears from the page.
- Data is preserved in the browser's memory by using localStorage.

2021-09-13 16:23 UTC, henatan99 requested changes
Hi @Adewunmi97 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>


## Required Changes ♻️
- [ ] A good descriptive readme is an important part of a preofessional repo. Kindly use the Microverse readme [template](https://github.com/microverseinc/readme-template) and add minimal description of your project. :pray: 
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- x
- y
- z

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-09-13 16:23 UTC, henatan99 commented on index.html
> +<body onload="startTime()">
- [ ] This `startTime()` function is throwing console error on the browser. Kindly fix it! :pray: 

![Screenshot from 2021-09-13 22-12-10](https://user-images.githubusercontent.com/64894927/133119600-a2503043-45fd-4f8d-bba1-d39ea1b3d2a1.png)

2021-09-13 16:23 UTC, henatan99 commented on main.js
> +    this.collection.push(newBook);
- [ ] OPTIONAL: Array `concat` method is preferred over `push` method for the sake of data integrity as it does not alter the original array. :+1:

2021-09-14 07:09 UTC, dasileker approved these changes
### **Hi @Adewunmi97 && @chuanqizhu0820,** 

### **Project Approved ✅**

![Approved](https://user-images.githubusercontent.com/61562626/133211360-39ee8dde-1233-4585-994f-753cc339b22e.gif)


### **Optional**

- Please remove the Onload=startTime() from your HTML body it causing a problem.

![kskska](https://user-images.githubusercontent.com/61562626/133211513-86466a9f-d2c8-4bec-ae67-8a26b8afe6d1.png)



Your project is complete!  There is nothing else to say other than... it's time to merge it 🚀
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-09-16 16:21 UTC, merged